# Generated by Django 2.2.2 on 2019-06-20 06:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190620_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='total_book_written',
            field=models.CharField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='generated unique id for book', primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Student name', max_length=100, null=True)),
                ('no_of_book_taken', models.CharField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five')], max_length=100, null=True)),
                ('Borrowed_date', models.DateField(auto_now=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='Author of book', on_delete=django.db.models.deletion.CASCADE, to='home.Author')),
                ('book_taken', models.ForeignKey(help_text='Book', on_delete=django.db.models.deletion.CASCADE, to='home.Book')),
            ],
        ),
    ]
