# Generated by Django 2.2.2 on 2019-06-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190620_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Borrowed_date',
            field=models.DateField(auto_now=True, null=True, verbose_name='Date'),
        ),
    ]
