# Generated by Django 2.2.2 on 2019-06-21 06:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20190621_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Borrowed_date',
            field=models.DateField(default=datetime.datetime(2019, 6, 21, 6, 50, 55, 215843, tzinfo=utc)),
        ),
    ]
