# Generated by Django 2.2.2 on 2019-06-22 04:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20190621_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Borrowed_date',
            field=models.DateField(default=datetime.datetime(2019, 6, 22, 4, 29, 2, 638086, tzinfo=utc)),
        ),
    ]
