# Generated by Django 2.2.2 on 2019-06-22 04:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20190622_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Borrowed_date',
            field=models.DateField(default=datetime.datetime(2019, 6, 22, 4, 45, 57, 274567, tzinfo=utc)),
        ),
    ]
