# Generated by Django 2.2.2 on 2019-06-22 09:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20190622_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Borrowed_date',
            field=models.DateField(default=datetime.datetime(2019, 6, 22, 9, 24, 41, 102493, tzinfo=utc)),
        ),
    ]
