# Generated by Django 2.2.2 on 2019-06-22 09:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20190622_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Borrowed_date',
            field=models.DateField(default=datetime.datetime(2019, 6, 22, 9, 30, 59, 505778, tzinfo=utc)),
        ),
    ]
