# Generated by Django 2.2.2 on 2019-06-23 09:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20190622_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Borrowed_date',
            field=models.DateField(default=datetime.datetime(2019, 6, 23, 9, 57, 22, 267965, tzinfo=utc)),
        ),
    ]
