# Generated by Django 2.2.2 on 2019-06-23 10:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20190623_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='username', max_length=30)),
                ('email', models.CharField(help_text='email', max_length=50)),
                ('password', models.CharField(help_text='Password', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='Borrowed_date',
            field=models.DateField(default=datetime.datetime(2019, 6, 23, 10, 18, 37, 486537, tzinfo=utc)),
        ),
    ]
