# Generated by Django 2.2.2 on 2019-06-23 18:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20190623_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Borrowed_date',
            field=models.DateField(default=datetime.datetime(2019, 6, 23, 18, 10, 46, 295403, tzinfo=utc)),
        ),
    ]
