# Generated by Django 2.2.2 on 2019-06-24 02:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20190623_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Borrowed_date',
            field=models.DateField(default=datetime.datetime(2019, 6, 24, 2, 51, 37, 263445, tzinfo=utc)),
        ),
    ]
